### ISSUE TITLE
Issue still not fixed

### ISSUE THREAD

**Issue by aymannajim** [Torca2001/MultiSelect#12]
Continuing this:
https://github.com/Torca2001/MultiSelect/issues/11

**Comment by Torca2001** [comment]
You mentioned this is the only plugin you have installed, do you not have the Zeres Plugin library installed?

https://rauenzi.github.io/BDPluginLibrary/release/0PluginLibrary.plugin.js
You can download it from this link and save it with Ctrl + S
Enable this plugin as well and see if it works.

**Comment by amau05** [comment]
Hi I confirm it doesn't work for me either. Zeres is installed both plugin are on, I'm the founder of the server, I select several users with ctrl and shift and right click. There is only the traditional move to as an option and it only move one user not all the users I selected.

**Comment by Torca2001** [comment]
Hmm I'm still struggling to recreate this with a fresh install.
Just confirming Multiselect is V1.2.0 and ZeresPluginLibrary is V2.0.17?

**Comment by amau05** [comment]
In my case yes I just checked. I was already using your plugin before the great nerf of the plugins by discord sometimes ago. I just reinstalled it recently from here (and manually activated it in the plugin section of my settings so it's on) . I don't think it's linked but I'm on windows 11, I don't know about you or ayman. I'm also in dev mode like ayman seem to be from his screenshot in the previous help topic.

**Comment by Torca2001** [comment]
I'm also running in dev mode, I can't imagine windows 11 would cause an issue.
Could you open you console since your running in dev and try to enable the plugin, see if any errors pop up in the console.
If turning on the plugin is fine then can you try to move yourself and again see if the console throws any kind of error.

**Comment by amau05** [comment]
Sadly not possible anymore it seem, I'm on the stable version. I use the dev mode because I sometime needs the IDs as I'm also an admin on a community server and I can't afford to have my discord client out of commission right now as I'm the only admin not on vacation at the moment... 

In 15 days if it's still not fixed we can see about it. But you will need to guide me a little in that case because I can use CLI on windows and a little on linux but I never used it on discord or anything chromium based.

**Comment by Torca2001** [comment]
Ah thats alright, at the moment hopefully I can recreate it otherwise I can't do much to fix it.

**Comment by aymannajim** [comment]
I'm on Windows 10 and it's not working for me either

**Comment by themegaxandy** [comment]
Working normally here. I select the users with shift + drag, and click the "Move X users here" button on the right mouse click on the target channel.

If the "Move X users here" option doesn't appear, I deactivate and reactivate the plugin. This solution always works for me.

I'm using MultiSelect v1.2.0 and ZeresPluginLibrary v2.0.17. Windows 11 build 22621. Discord v1.0.9016. BetterDiscord v1.9.3.

**Comment by amau05** [comment]
Just tried 3 times to disable and enable the plugin, still nothing

**Comment by Torca2001** [comment]
#14 Possibly fixed

**Comment by amau05** [comment]
![ice_screenshot_20231120-234044](https://github.com/Torca2001/MultiSelect/assets/110784365/b6df43ac-29ab-4644-ae86-94fbe45ce985)

Still nothing (sorry it's in french right now...) I tried right clicking on me or on another user, same thing.

**Comment by Torca2001** [comment]
It looks like your right clicked on a user, can you try it on a vc channel?
![image](https://github.com/Torca2001/MultiSelect/assets/26198364/dc903113-cce9-48b7-b56d-6ea5eb5281a8)

**Comment by themegaxandy** [comment]
I can confirm that it works again after the last update. I had to deactivate and activate the plugin for the option to appear, but it worked normally from then on.

**Comment by amau05** [comment]
Same, now it works. I was indeed looking at the wrong place...

**Comment by Torca2001** [comment]
Awesome I'm going to consider this closed, the original issue was likely discord pushing silent beta tests to specific people.
